language: node_js
sudo: false
node_js:
  - "9.4"
before_install:
  - npm install --save alex               # http://alexjs.com/
  - npm install --save mdast mdast-lint   # https://github.com/wooorm/mdast#readme
  
install:
  - npm install
script:
  - npm test
